version: '3.8'

volumes:
  pgdata:

services:
  db:
    image: postgres:alpine
    ports:
      - 5439:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asincio_bd
